# -*- coding: utf-8 -*-
"""practicepy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nyXCFaXojy5lz3p0WG9HGtNBAH8g1zy3
"""

n=input()
rev=n[::-1]
if(n==rev):
  print("palindrome")
else:
  print("not a palindrome")

n=int(input())
fact=1
for i in range(1,n+1):
  fact=fact*i
print(fact)

x=int(input())
y=int(input())
if(x>y):
  print(x)
else:
  print(y)

n=int(input())
m=len(str(n))
a=0
t=n
while(t>0):
  u=t%10
  l=u**m
  a+=l
  t//=10
if(a==n):
  print("armstrong number")
else:
  print("not armstrong")

c=int(input())
f=c*9/5+32
print(f"c{c}->f{f}")

f=int(input())
c=(f-32)*5/9
print(f"f{f}->c{c}")

a=int(input("enter A:"))
b=int(input("enter B:"))
a,b=b,a
print(f"a={a},b={b}")

n=int(input())
a=0
b=1
print(a)
print(b)
for i in range(1,n-1):
  next=a+b
  a=b
  b=next
  print("",next)

n=input()
count=0
vowels=['a','e','i','o','u']
for i in n:
  if i.lower() in vowels:
    print(i)
    count+=1
print(count)

a=[3,17,29,7,65,92]
print(max(a))
print(min(a))

from binascii import b2a_uu
def add(a,b):
  return a+b
def sub(a,b):
  return a-b
def mul(a,b):
  return a*b
def div(a,b):
  return a/b
a=int(input())
b=int(input())
print(add(a,b))
print(sub(a,b))
print(mul(a,b))
print(div(a,b))

a=int(input())
b=int(input())
x=a
y=b
while y!=0:
  x,y=y,x%y
gcd=x
lcm=(a*b)//gcd
print("gcd:",gcd)
print("lcm",lcm)

n=int(input())
if(n>0):
  print("positive")
elif(n<0):
  print("negitive")
else:
  print("zero")

n=int(input())
if(n%4==0):
  print("Leap Year")
else:
  print("Not a Leap Year")

n=int(input())
if(n%2==0):
  print("Even")
else:
  print("Odd")

word1=input()
word2=input()
s1=sorted(word1)
s2=sorted(word2)
if(s1==s2):
  print("Anagram")
else:
  print("not anagram")

n=int(input())
for i in range(1,n+1):
  for j in range(1,i+1):
    print(j,end="")
  print()

n=int(input())
for i in range(1,n+1):
  print(" "*(n-i)+"* "*i)
for i in range(n-1,0,-1):
  print(" "*(n-i)+"* "*i)

n=int(input())
for i in range(n):
  print(" "*i+"*"*(n-i))

x=int(input())
y=int(input())
z=int(input())
a=max(x,y,z)
print(a)

n=int(input())
s=n**0.5
if(s==n):
  print("sqare root num")

from collections import Counter
a=input()
b=input()
if(Counter(a)==Counter(b)):
  print("Anagram")

s=input()
l=""
for i in range(len(s)):
  cur=""
  for j in range(i,len(s)):
    if s[j] not in cur:
      cur+=s[j]
      if len(cur)>len(l):
        l=cur
print(len(l))

s=int(input())
s1=s.lower()
v=['a','e','i','o','u']
l=[]
r=0
sl=list(s1)
for i in s1:
  if(i in v):
    l.append(i)
for i in range(len(s)-1,-1,-1):
  if(i )

n=int(input())
x=list(map(int,input().split()))
for i in range(n):
  for j in range(i+1,n):
    if(x[i]==x[j]):
      print(x[i])

s = input()
for i in range(len(s)):
    for j in range(i + 1, len(s) + 1):
        sub = s[i:j]
        if sub == sub[::-1]:
         print(sub)

class student:
  def __init__(self,name,age):
    self.name=name
    self.age=age

  def display(self):
    print("Name:",self.name)
    print("Age:",self.age)
obj=student("hems",3)
obj.display()

class Father:
  def bike(self):
    print("Father has Bike")
class son(Father):
  def cycle(self):
    print("Son has cycle")
obj=son()
obj.bike()

class Father:
  def property(self):
    print("Father Property")
class son(Father):
  pass
obj=son()
obj.property()

class bank:
  def __init__(self):
    self.__balance=5000
  def show_balance(self):
    print("balance",self.__balance)
obj=bank()
obj.show_balance()

class multiply:
  def product(self,a=None,b=None,c=None):
    if a and b and c:
      print("product=",a*b*c)
    elif a and b:
      print("product=",a*b)
    else:
      print("Invalid Input")
obj=multiply()
obj.product(10,20,30)
obj.product(10,20)

n=int(input())
s=str(n)
rev=s[::-1]
if(n>1):
  for i in range(2,n):
    if(n%i==0 and int(rev)%i==0):
      print("not prime")
      break
  else:
    print("prime")
else:
  print("not prime")

n=int(input())
a=0
for i in range(1,n+1):
    if(i%2==0):
      a=-i
    else:
      a=i
    print(a)

n=int(input())
s1=str(n)
r1=s1[::-1]
sq1=n**2
sq2=int(r1)**2
s2=str(sq2)
r2=s2[::-1]
if(sq1==int(r2)):
  print("adam number")
else:
  print("not an adam number")

def card(st):
  if(len(st)<=4):
    return st
  else:
    return "#"*(len(st)-4)+st[-4:-1]
st=input()
print(card(st))

